CREATE DATABASE InLock_Games_Tarde;
GO

USE InLock_Games_Tarde;
GO

CREATE TABLE Estudios
(
	IdEstudio	INT PRIMARY KEY IDENTITY,
	NomeEstudio	VARCHAR(255) NOT NULL UNIQUE	
);
GO

CREATE TABLE Jogos
(
	IdJogo			INT PRIMARY KEY IDENTITY,
	NomeJogo		VARCHAR(255) NOT NULL,
	Descricao		VARCHAR(255) NOT NULL,
	DataLancamento	DATE NOT NULL,
	Valor			MONEY NOT NULL,
	IdEstudio		INT FOREIGN KEY REFERENCES Estudios (IdEstudio)
);
GO

CREATE TABLE TipoUsuarios
(
	IdTipoUsuario		INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario	VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Usuarios
(
	IdUsuario		INT PRIMARY KEY IDENTITY,
	Email			VARCHAR(200) NOT NULL UNIQUE,
	Senha			VARCHAR(20) NOT NULL,
	IdTipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuarios (IdTipoUsuario)
);